# Generated by Django 2.2.10 on 2021-09-27 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start', models.DateField()),
                ('finish', models.DateField()),
                ('desc', models.TextField()),
            ],
            options={
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='Vopros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vopros', models.TextField()),
                ('tip', models.CharField(choices=[('00', 'Текст'), ('01', 'Один'), ('02', 'Много')], max_length=2)),
                ('opros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fr.Opros')),
            ],
        ),
        migrations.CreateModel(
            name='Otvet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_polzovatel', models.IntegerField()),
                ('otvet', models.CharField(max_length=1000)),
                ('vopros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fr.Vopros')),
            ],
        ),
    ]
