# Generated by Django 2.2.10 on 2021-09-27 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fr', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otvet',
            old_name='id_polzovatel',
            new_name='user_id',
        ),
    ]
