# Generated by Django 2.2.10 on 2021-09-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fr', '0002_auto_20210927_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='vopros',
            name='standart_otvet',
            field=models.CharField(default=None, max_length=1000, null=True),
            preserve_default=False,
        ),
    ]
